"""initial_schema

Revision ID: 706d58a068c7
Revises:
Create Date: 2026-04-12 18:52:28.650186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "706d58a068c7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "h3_cells",
        sa.Column("h3_index", sa.String(length=15), nullable=False),
        sa.Column("resolution", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("h3_index"),
    )
    op.create_table(
        "listings_raw",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("area_total", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("area_kitchen", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("rooms", sa.Integer(), nullable=True),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("floors_total", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("address_text", sa.Text(), nullable=True),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("material_type", sa.String(length=50), nullable=True),
        sa.Column("images_count", sa.Integer(), nullable=True),
        sa.Column("has_photos", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "parsed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("normalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id"),
    )
    op.create_table(
        "price_chunks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rooms_number", sa.Integer(), nullable=False),
        sa.Column("min_price", sa.BigInteger(), nullable=False),
        sa.Column("max_price", sa.BigInteger(), nullable=False),
        sa.Column("listings_count", sa.Integer(), nullable=False),
        sa.Column("scraped", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rooms_number", "min_price"),
    )
    op.create_table(
        "buildings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("h3_index", sa.String(length=15), nullable=True),
        sa.Column("h3_index_r11", sa.String(length=15), nullable=True),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("floors_total", sa.Integer(), nullable=True),
        sa.Column("material_type", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["h3_index"],
            ["h3_cells.h3_index"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("h3_index_r11"),
    )
    op.create_table(
        "liquidity_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("h3_index", sa.String(length=15), nullable=False),
        sa.Column("rooms", sa.Integer(), nullable=False),
        sa.Column("avg_days_on_market", sa.Integer(), nullable=True),
        sa.Column("median_days", sa.Integer(), nullable=True),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["h3_index"],
            ["h3_cells.h3_index"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("h3_index", "rooms"),
    )
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("h3_index", sa.String(length=15), nullable=False),
        sa.Column("rooms", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "median_price_per_m2", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["h3_index"],
            ["h3_cells.h3_index"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("h3_index", "rooms", "date"),
    )
    op.create_table(
        "price_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("h3_index", sa.String(length=15), nullable=False),
        sa.Column("rooms", sa.Integer(), nullable=False),
        sa.Column("avg_price_per_m2", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "median_price_per_m2", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("listings_count", sa.Integer(), nullable=False),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["h3_index"],
            ["h3_cells.h3_index"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("h3_index", "rooms"),
    )
    op.create_table(
        "flats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("area_total", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("area_kitchen", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("rooms", sa.Integer(), nullable=True),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_flats_building_rooms_floor",
        "flats",
        ["building_id", "rooms", "floor"],
        unique=False,
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("raw_id", sa.Integer(), nullable=False),
        sa.Column("flat_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("price_per_m2", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["flat_id"],
            ["flats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_id"],
            ["listings_raw.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("raw_id"),
    )
    op.create_table(
        "deal_analysis",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column(
            "median_price_per_m2", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "actual_price_per_m2", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("is_hot_deal", sa.Boolean(), nullable=False),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("listing_id"),
    )
    op.create_table(
        "listing_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "is_online",
            sa.Boolean(),
            nullable=False,
            comment="False — объявление пропало в этом проходе",
        ),
        sa.Column(
            "seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "price_predictions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "listing_id",
            sa.Integer(),
            nullable=True,
            comment="Для пост-фактум верификации точности прогноза",
        ),
        sa.Column(
            "input_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("predicted_price", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price_predictions")
    op.drop_table("listing_snapshots")
    op.drop_table("deal_analysis")
    op.drop_table("listings")
    op.drop_index("ix_flats_building_rooms_floor", table_name="flats")
    op.drop_table("flats")
    op.drop_table("price_stats")
    op.drop_table("price_history")
    op.drop_table("liquidity_stats")
    op.drop_table("buildings")
    op.drop_table("price_chunks")
    op.drop_table("listings_raw")
    op.drop_table("h3_cells")
    # ### end Alembic commands ###
